JBSWU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('faq/', include('faq.urls', namespace="faq")),
    path('main/', include('main.urls', namespace="main")),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace="auth")),
    path('accounts/', include(('accounts.urls'), namespace="accounts")),
    path('qna/', include(('qna.urls'))),
    path('problem/', include('problem.urls', namespace="problem")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('editinfo/', views.editinfo, name="editinfo"),
]

faq/urls.py
# 17줄은 원래 있는거 주석처리
from django.urls import path

from . import views

app_name = 'faq'

urlpatterns = [
    path('', views.index, name='index'),
]

main/urls.py
from django.urls import path, include
from . import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/',views.about, name='about'),
]

problem/urls.py
from django.urls import path, include

from . import views

app_name = 'problem'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('sns/', views.sns, name='sns'),
    path('sns/<int:number>', views.sns, name='sns'),
    
    path('article/<int:number>', views.article, name='article'),
    
    path('literacy/', views.literacy, name='literacy'),
    path('literacy/<int:number>', views.literacy, name='literacy'),
    
    path('community/', views.community, name='community'),
    path('community/<int:number>', views.community, name='community'),
]

main/models.py
from django.db import models
# Create your models here.

main/views.py
from django.shortcuts import render


def index(request):
    return render(
        request,
        'main/index.html',
    )

def about(request):
    return render(
        request,
        'main/about.html',
    )

main/templates/main/about.html
{% extends 'main/base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css">
    <title>About</title>
</head>
<body>
<style>
    
    .swiper-container{
      width: 100%; 
      height: 100%;
    }

    .swiper-slide { 
        padding: 50px;
    }
    
    .swiper-button-prev{
        color: "#fffff" !important;
    }
    </style>
<br><br>

<div class="swiper-container">
    <div class="swiper-wrapper">

        
        <div class="swiper-slide"  style="width:700px">
            <div class="card border-primary mb-2" style="">
                <div class="card-header" style="font-size:30px;">리터러시란?</div>
                <div class="card-body">
                    <h4 class="card-title">+ 디지털 리터러시란 디지털 기술, 데이터, 정보, 콘텐츠, 미디어를 읽고, 분석하고, 쓸 줄 아는 능력과 소양을 말합니다. </h4><hr>
                    <p class="card-text" style="font-size:20px;"><strong>리터러시란 글을 읽고 쓸 줄 아는 능력을 말합니다.</strong> 미래는 디지털 리터러시, 즉 디지털을 읽고 분석하고, 쓸 줄 아는 능력이 중요합니다. 특히 코로나19의 상황에서 원격 수업과 원격 정보 제공 등에 따른 디지털 정보와 지식의 격차는 스마트폰, 사물인터넷, 빅데이터, 5G, 가상현실과 같은 기술이 발달함에 따라 대두되는 문제입니다.<br><br>누군가 만들어낸 디지털 기술을 이용하고 디지털 데이터, 정보, 콘텐츠를 디지털 미디어를 통해 일방적, 수동적으로 소비하기만 했다면, 앞으로는 소비자에서 생산자로 거듭나 누구나 디지털 기술, 데이터, 정보, 콘텐츠를 생산하고 디지털 미디어를 통해 공유하는 능력을 갖춰야 합니다. <strong>디지털 세상에 넘쳐나는 허위정보를 스스로 구별해내고 누군가의 주장에 대해 스스로 판단하는 능력도 갖춰야 합니다.</strong><br></p>
                </div>
            </div>
        </div>

        
        <div class="swiper-slide">
            <div class="card border-secondary mb-3" style="">
                <div class="card-header"style="font-size:30px;">리터러시 공부해야 하는 이유</div>
                <div class="card-body">
                    <h4 class="card-title">+ 리터러슈는 다음과 같은 이유로 리터러시 교육을 제공하는 사이트 입니다.</h4><hr>
                    <p class="card-text"style="font-size:20px;">미디어 리터러시는 뉴스 리터러시에서 출발한다. 뉴스를 통해 새 정보를 받아들이는 환경에서 각 구성원이 얼마나 활용능력과 주체적 수용 능력을 갖췄느냐가 중요합니다. 디치털과 스마트폰 환경에서 대부분의 뉴스 이용은 디지털로 매개되는 만큼 뉴스를 제대로 읽는 능력은 디지털 리터러시와 분리될 수 없습니다.<br><br>가짜 뉴스 사태는 디지털 리터러시와 뉴스 리터러시가 얼마나 중요한지 알려주는 사례입니다. 시민의 지적 역량과 학습 능력이 한 사회와 국가의 현재와 미래의 운명에 영향을 준다. 디지털 시민성을 높이기 위해서 모든 시민에게 디지털 리터러시의 중요성을  일깨우는 사회적 노력이 요구되는 이유입니다.<br><br></p>
                </div>
            </div>
        </div>

        
        <div class="swiper-slide">
            <div class="card border-success mb-3" style="">
                <div class="card-header"style="font-size:30px;">리터러시 분야-1</div>
                <div class="card-body">
                    <h4 class="card-title">+ 디지털 리터러시 협회에서는 기준으로 하는 리텉러시 5가지 분야입니다.</h4><hr>
                    <p class="card-text"style="font-size:20px;">
                        digital technology literacy<br>&nbsp;:&nbsp;인공지능, 가상현실, 증강현실, 3D 프린터, 드론과 같은 4차 산업 혁명의 기술들을 이해하고 이러한 순기능, 역기능을 이해하고 순기능을 강화하고 역기능을 약화시키기 위해서 디지털기술에 대한 인문학적 사고가 필요합니다.<br><br>
                        digital data literacy<br>&nbsp;:&nbsp;불확실성, 허위정보 늘어나는데 사실기반 사고가 중요해지고 있다. 모든 데이터가 디지털화 되어 있고 디지털 데이터를 조사 분석해서 합리적결론 도출하는 능력이 필요합니다.<br><br>
                        digital media literacy<br>&nbsp;:&nbsp;디지털 미디어상 데이터정보,지식을 비판적 주체적으로 판단하는 것도 중요하고 데이터 지식, 정보들을 잘 찾고 활용하고 공유하는 능력 또한 디지털 리터러시에 포함됩니다.<br><br>
                </div>
            </div>
        </div>

                <div class="swiper-slide">
            <div class="card border-success mb-3" style="">
                <div class="card-header"style="font-size:30px;">리터러시 분야-2</div>
                <div class="card-body">
                    <h4 class="card-title">+ 디지털 리터러시 협회에서는 기준으로 하는 리텉러시 5가지 분야입니다.</h4><hr>
                    <p class="card-text"style="font-size:20px;">
                        digital content literacy<br>&nbsp;:&nbsp;데이터 가공하면 정보가 되고 정보를 체계화하면 지식이 됩니다.특정 소재나 내용에 여러가지 문화적 공정을 거처 가치를 부여하거나 가치를 드높인것을 말합니다. 이러한 컨텐츠를 만들어내는 능력을 디지털 컨텐츠 리터러시라고 합니다.<br><br>
                        digital communication literacy<br>&nbsp;:&nbsp;디지털로 업무를 보게 될때, 디지털 공간에서의 매너를 지키는것도 중요합니다. 디지털에서 커뮤니케이션에서 미디어 특성 고려하면서 사용해야 합니다. <br><br>
                    </p>
                </div>
            </div>
        </div>
        
        

        <div class="swiper-slide">
            <div class="card border-warning mb-3" style="">
                <div class="card-header"style="font-size:30px;">리터러시의 개념 확장 과정</div>
                <div class="card-body">
                    <h4 class="card-title">+ 필란드, 영국, 프랑스, 캐나다, 호주등 해외 주요국들 또한 디지털 사회에서 디지털 기술을 책임있고 안전하게 이용하는것을 중시하고 있습니다.</h4><hr>
                    <p class="card-text"style="font-size:20px;">미국의 미디어리터러시교육협회는 미디어 리터러시를 “모든 형태의 커뮤니케이션을 하는 데 있어 접근, 분석, 평가, 창조, 행동하는 능력”이라고 정의하고 있습니다. 여기서 말하는 모든 형태의 커뮤니케이션은 문자를 중심으로 한 인쇄 매체뿐만 아니라 PC, 스마트폰, 태블릿 등 다양한 멀티미디어들을 활용하는 행위를 내포하고 있는데, 결국 미디어 리터러시라는 것이 문자를 포함한 물리적 미디어들의 진화에 따라 지속적으로 변화하는 유동적 개념임을 알 수 있습니다. <br>지금까지의 미디어 환경을 돌이켜 보면 최근 20년 동안 두 번의 큰 변화가 있었는데 첫 번째는 1990년대 말부터 2000년대 초반 인터넷의 도입이고, 두 번째는 2000년대 말부터 2010년대 초반의 스마트폰의 출시입니다. 텔레비전과 영화 등을 중심으로 논의되어온 <strong>미디어 리터러시는 인터넷이 도입되면서 디지털 리터러시라는 개념으로 확장</strong>되었고, 스마트폰이 대중화되면서 소셜미디어 리터러시로 정교화되었습니다. 최근에는 이른바 지능정보사회로 일컬어지는 새로운 사회에 대한 담론들과 4차산업혁명, 인공지능과 같은 첨단 이슈들이 등장하면서 그에 걸맞은 새로운 미디어 리터러시의 필요성이 요구되고 있습니다. <br> </p>
                </div>
            </div>
        </div>
    </div>

    <!-- If we need pagination -->
    <div class="swiper-pagination"></div>

    <!-- If we need navigation buttons -->
    <br><br><br><br>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    <br><br><br><br>
</div><br><br><br><br>

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
        var mySwiper = new Swiper('.swiper-container', {
// 슬라이드를 버튼으로 움직일 수 있습니다.
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },
    
// 현재 페이지를 나타내는 점이 생깁니다. 클릭하면 이동합니다.
  pagination: {
    el: '.swiper-pagination',
    type: 'bullets',
  },

// 현재 페이지를 나타내는 스크롤이 생깁니다. 클릭하면 이동합니다.
  scrollbar: {
    el: '.swiper-scrollbar',
    draggable: true,
  },
});
    </script>
</body>
</html>
{% endblock %}	

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8"/>
    <title>{% block title %}리터러슈{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/prism-okaidia.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/custom.min.css' %}">

</head>
<body>
    
<style>
    .custom2{
        display:inline !important;
    }

</style>
<div class="navbar navbar-expand-lg fixed-top navbar-light bg-light" id="navbar">
    <div class="container-fluid">
        <a href="{% url 'main:index' %}" class="navbar-brand">리터러슈</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:about' %}">About</a>
                </li>
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"> Question <span class="caret"></span></a>
                        <div class="dropdown-menu" aria-labelledby="download">
                            <a class="dropdown-item" href="{% url 'faq:index' %}">FAQ</a>
                            <a class="dropdown-item" href="{% url 'writepage' %}">Q&A</a>
                        </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'problem:index' %}">Problem </a>
                </li>

            </ul>
            <ul class="navbar-nav ms-md-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" id="download">{{ user }}<span class="caret"></span></a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'accounts:editinfo' %}">회원정보</a>
                            <a class="dropdown-item" href="{% url 'auth:logout' %}">로그아웃</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown">계정<span class="caret"></span></a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'auth:login' %}">로그인</a>
                            <a class="dropdown-item" href="{% url 'accounts:signup' %}">회원가입</a>
                        </div>
                    </li>
                {% endif %}
                <form action="/qna/writepage" method="get" style="text-align:right;">
                    <input type="text" name="q" value="{{ q }}" class="input-text">
                    <input type="submit" value="검색" class="custom2 btn btn-sm btn-outline-primary">
                </form>
            </ul>
        </div>
    </div>
</div>


<div class ="container">
    <div class="row">
        <div class="col-lg" id="main.div">
            <center><img src="{% static 'main/img/swucream.png' %}" style="max-width:15%; height:auto;"></center>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg" id="main.div">
            {% block content %}
            <h5>Content - block content end block을 통해서 작성하세요</h5>
            {% endblock %}
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg" id="main.div">
            <center>
                <a href="#" target="_blank">
                    <img src="{% static 'main/img/swucream_ad.png' %}" style="max-width:35%; height:auto;">
                </a>
            </center>
        </div>
    </div>
    
     <div class="row">
        <div class="col-lg" id="main.div">
            <center>
                <a href="https://securecoding.software/" target="_blank">
                    <img src="{% static 'main/img/sgd.png' %}" style="max-width:35%; height:auto;">
                </a>
            </center>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg">
            <center>
            <table width=500px>
                <tr>
                    <td><center><a href="https://www.mois.go.kr/" target="_blank"><img src="{% static 'main/img/mois_logo.png' %}" style="max-width:100%; height:auto;" ></a></center></td>
                    <td><center><a href="https://www.kisa.or.kr/" target="_blank"><img src="{% static 'main/img/kisa_logo.png' %}" style="max-width:100%; height:auto;"></a></center></td>
                    <td><center><a href="https://kiisc.or.kr/" target="_blank"><img src="{% static 'main/img/kiisc_logo.png' %}" style="max-width:100%; height:auto;"></a></center></td>
                </tr>
            </table>
            </center>
        </div>
    </div>
    
    <br><br><br><br><br>
    
</div>

    <script src="{% static 'main/js/jquery.min.js' %}"></script>
    <script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>

    <script src="{% static 'main/js/prism.js' %}"></script>
    <script src="{% static 'main/js/custom.js' %}"></script>

</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %}리터러슈 - 문제 풀기{% endblock %}
{% load static %}

{% block content %}

<script>
    function prog()
    {
        var value = [{{ user.profile.score1 }},{{ user.profile.score2 }},{{ user.profile.score3 }},{{ user.profile.score4 }},{{ user.profile.score5 }},{{ user.profile.score6 }},{{ user.profile.score7 }},{{ user.profile.score8 }},{{ user.profile.score9 }},{{ user.profile.score10 }},{{ user.profile.score11 }},{{ user.profile.score12 }}];
        var value2 = value.filter(n => n === 1).length;
        var value3 = value2*8.4;

        var progr = document.getElementById('progress');

        progr.innerHTML = '<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="'+value3+'" aria-valuemin="0" aria-valuemax="100" style="width: '+value3+'%;"></div>';
    };
</script>
<br>
<div class="progress" id="progress"> <!--8.4%-->
</div>

<table class="table table-hover">
    <th></th><th></th><th scope="row" style="font-size: 30pt; text-align: center;">Literacy</th><th></th><th></th>
    <tr>
        <td style="width: 35%"></td>
        {% if user.profile.score1 == 1 %} 
        <td><a href="{% url 'problem:literacy' number=1 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:literacy' number=1 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        {% if user.profile.score2 == 1 %} 
        <td><a href="{% url 'problem:literacy' number=2 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:literacy' number=2 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        {% if user.profile.score3 == 1 %} 
        <td><a href="{% url 'problem:literacy' number=3 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:literacy' number=3 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        <td style="width: 35%"></td>
    </tr>
    
    <th></th><th></th><th scope="row" style="font-size: 30pt; text-align: center;">Article</th><th></th><th></th>
    <tr>
        <td></td>
        {% if user.profile.score4 == 1 %} 
        <td><a href="{% url 'problem:article' number=1 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:article' number=1 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        {% if user.profile.score5 == 1 %} 
        <td><a href="{% url 'problem:article' number=2 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:article' number=2 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        {% if user.profile.score6 == 1 %} 
        <td><a href="{% url 'problem:article' number=3 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:article' number=3 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        <td></td>
        
    </tr>
    
    <th></th><th></th><th scope="row" style="font-size: 30pt; text-align: center;">Community</th><th></th><th></th>
    <tr>
        <td></td>
        {% if user.profile.score7 == 1 %} 
        <td><a href="{% url 'problem:community' number=1 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:community' number=1 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        
        {% if user.profile.score8 == 1 %} 
        <td><a href="{% url 'problem:community' number=2 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:community' number=2 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        
        {% if user.profile.score9 == 1 %} 
        <td><a href="{% url 'problem:community' number=3 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:community' number=3 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        <td></td>
    </tr>
    
    <th></th><th></th><th scope="row" style="font-size: 30pt; text-align: center;">SNS</th><th></th><th></th>
    <tr>
        <td></td>
        {% if user.profile.score10 == 1 %} 
        <td><a href="{% url 'problem:sns' number=1 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:sns' number=1 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        {% if user.profile.score11 == 1 %} 
        <td><a href="{% url 'problem:sns' number=2 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:sns' number=2 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        {% if user.profile.score12 == 1 %} 
        <td><a href="{% url 'problem:sns' number=3 %}"><img src="{% static 'main/img/swucream_prob.png' %}" style="width:200px"></a></td>
        {% else %} 
        <td><a href="{% url 'problem:sns' number=3 %}"><img src="{% static 'main/img/swucream_prob2.png' %}" style="width:200px"></a></td>
        {% endif %}
        <td></td>
    </tr>
</table>
<script>prog();</script>
{% endblock %}